export const SERVER_PORT = 'PORT'
export const JWT_SECRET = 'JWT_SECRET'
export const DATABASE_HOST = 'DATABASE_HOST';
export const DATABASE_PORT = 'DATABASE_PORT';
export const DATABASE_USERNAME = 'DATABASE_USERNAME';
export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const DATABASE_NAME = 'DATABASE_NAME';
export const DEFAULT_USER_SUPER_ADMIN = 'DEFAULT_USER_SUPER_ADMIN';
export const DEFAULT_SUPER_ADMIN_PASSWORD = 'DEFAULT_SUPER_ADMIN_PASSWORD';

export const DEFAULT_EMPLEADO_NAME = 'DEFAULT_EMPLEADO_NAME';
export const DEFAULT_EMPLEADO_LASTNAME = 'DEFAULT_EMPLEADO_LASTNAME';
export const DEFAULT_EMPLEADO_EMAIL = 'DEFAULT_EMPLEADO_EMAIL';


export const AWS_REGION='AWS_REGION'
export const AWS_ACCESS_KEY_ID='AWS_ACCESS_KEY_ID'
export const AWS_SECRET_ACCESS_KEY='AWS_SECRET_ACCESS_KEY'
export const AWS_PUBLIC_BUCKET_NAME='AWS_PUBLIC_BUCKET_NAME'